# Site Settings
title:               "Lee Clement"
tagline:             "a Ph.D. Candidate at the University of Toronto"
description:         "Ph.D. Candidate in Mobile Robotics at the University of Toronto"
baseurl:             # /
url: 			           # http://leeclem.net
github:
  repo:              "https://github.com/leeclemnet/leeclemnet.github.io"
author:
  name:              "Lee Clement"
  email:             "lee.clement@mail.utoronto.ca"
  twitter:           "leeclemnet"
  instagram:         
  github:            "leeclemnet"
  facebook:          
  linkedin:          "leeclemnet"
  scholar:           "skVilbAAAAAJ"
paginate:            5

# Custom vars
version:             3.0.0

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate]
