# Site Settings
title:               "Lee Clement"
tagline:             "Ph.D. Candidate in Robotics at the University of Toronto"
description:         "Lee Clement is a Ph.D. Candidate in Robotics at the University of Toronto, supervised by Prof. Jonathan Kelly. His research interests include mobile robotics, state estimation, computer vision and machine learning."
baseurl:             # /
url: 			           # http://leeclem.net
github:
  repo:              "https://github.com/leeclemnet/leeclemnet.github.io"
author:
  name:              "Lee Clement"
  email:             "lee.clement@mail.utoronto.ca"
  twitter:           "leeclemnet"
  instagram:         
  github:            "leeclemnet"
  facebook:          
  linkedin:          "leeclemnet"
  scholar:           "skVilbAAAAAJ"
paginate:            15
paginate_path:       "/blog/page:num/"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
plugins:             [jekyll-paginate]

# Collections
collections:
  - research
  - teaching
  - service